# Generated by Django 4.1.3 on 2022-11-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0002_user_abonnement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='abonnement',
        ),
    ]
