# Generated by Django 4.1.3 on 2022-11-09 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0003_remove_user_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abonnement',
            field=models.ManyToManyField(through='connexion.Abonnement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qui_suit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='user_suivi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_par', to=settings.AUTH_USER_MODEL),
        ),
    ]
