# Generated by Django 4.1.3 on 2022-11-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critique',
            old_name='titre',
            new_name='entete',
        ),
    ]
